/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import taxi.Taxi;

/**
 *
 * @author Alex
 */
public class Input extends javax.swing.JFrame {

    
    private static Taxi simulation;
    /**
     * Creates new form Input
     */
    public Input() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taxiModeGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btn_animate = new javax.swing.JButton();
        tf_animate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_path = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btn_route = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        rb_parade = new javax.swing.JRadioButton();
        rb_search = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        tf_cantClients = new javax.swing.JTextField();
        btn_cantClients = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_origin = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf_destiny = new javax.swing.JTextField();
        btn_addClient = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        tf_park = new javax.swing.JTextField();
        btn_park = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_mode = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Animar");

        btn_animate.setText("Enviar");
        btn_animate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_animateActionPerformed(evt);
            }
        });

        tf_animate.setText("0");
        tf_animate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_animateActionPerformed(evt);
            }
        });

        jLabel2.setText("Mostrar");

        btn_path.setText("Apagado");
        btn_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pathActionPerformed(evt);
            }
        });

        jLabel3.setText("Ruta");

        btn_route.setText("Apagado");
        btn_route.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_routeActionPerformed(evt);
            }
        });

        jLabel4.setText("Modo");

        taxiModeGroup.add(rb_parade);
        rb_parade.setText("Pasear");

        taxiModeGroup.add(rb_search);
        rb_search.setText("Buscar clientes");
        rb_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_searchActionPerformed(evt);
            }
        });

        jLabel5.setText("Cant. clientes");

        btn_cantClients.setText("Enviar");
        btn_cantClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cantClientsActionPerformed(evt);
            }
        });

        jLabel6.setText("Origen");

        jLabel7.setText("Destino");

        btn_addClient.setText("Enviar");
        btn_addClient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addClientActionPerformed(evt);
            }
        });

        jLabel8.setText("Parquear");

        btn_park.setText("Enviar");
        btn_park.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parkActionPerformed(evt);
            }
        });

        jLabel9.setText("Agregar clientes");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jScrollPane1.setViewportView(jTextArea1);

        btn_mode.setText("Enviar");
        btn_mode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modeActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Taxi");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addComponent(tf_animate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_animate)
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btn_path))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_route)
                            .addComponent(jLabel3))
                        .addContainerGap(199, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(tf_park, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_park))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(rb_parade)
                                .addGap(18, 18, 18)
                                .addComponent(rb_search)
                                .addGap(18, 18, 18)
                                .addComponent(btn_mode)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tf_origin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(tf_destiny, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_addClient))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(tf_cantClients, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_cantClients)))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(btn_animate)
                        .addComponent(tf_animate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_route))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_path)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(tf_cantClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_cantClients))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(tf_origin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(tf_destiny, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_addClient))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(rb_parade)
                            .addComponent(rb_search)
                            .addComponent(btn_mode))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel8)
                            .addComponent(tf_park, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_park))))
                .addGap(90, 90, 90)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_searchActionPerformed

    private void tf_animateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_animateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_animateActionPerformed

    private void btn_animateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_animateActionPerformed
       int numAnimate = -1;
        try{
            numAnimate = Integer.parseInt(tf_animate.getText());
        }catch(Exception e){
            System.out.println("Error: numero incorrecto");
        }        
               
        if(numAnimate >= 0){
            simulation.setDaemon(numAnimate);
            System.out.println(simulation.getDaemon());
        }else{
            //Valor invaludo
            System.out.println("Error: numero incorrecto");
        }
            
        
    }//GEN-LAST:event_btn_animateActionPerformed

    private void btn_parkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parkActionPerformed

        if(tf_park.getText().toString().length() != 0){
            char destiny = tf_park.getText().toString().charAt(0);
            if(!simulation.park(destiny)){
                System.out.println("Error: Destino \'" + destiny + "\' es invalido para parquear");
            }
        } 

    }//GEN-LAST:event_btn_parkActionPerformed

    private void btn_modeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modeActionPerformed
        if(rb_parade.isSelected()){
            simulation.parade();
        }else if (rb_search.isSelected()){
            simulation.searchClient();
        }else{
            System.out.println("Error: ninguna opcion seleccionada");
        }
    }//GEN-LAST:event_btn_modeActionPerformed

    private void btn_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pathActionPerformed
        simulation.switchPath();
        if(simulation.getPathOn()){
            btn_path.setText("Encendido");
        }else{
            btn_path.setText("Apagado");
        }
    }//GEN-LAST:event_btn_pathActionPerformed

    private void btn_routeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_routeActionPerformed
        simulation.switchRoute();
        if(simulation.getRouteOn()){
            btn_route.setText("Encendido");
        }else{
            btn_route.setText("Apagado");
        }
    }//GEN-LAST:event_btn_routeActionPerformed

    private void btn_cantClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cantClientsActionPerformed
        int numClients = -1;
        try{
            numClients = Integer.parseInt(tf_cantClients.getText());
        }catch(Exception e){
            //Notify errot
            System.out.println("Error: cantidad de clientes incorrecta");
        }        
               
        if(numClients >= 0){
            simulation.addClients(numClients);
        }else{
            //Valor invaludo
            System.out.println("Error: cantidad de clientes incorrecta");
        }
    }//GEN-LAST:event_btn_cantClientsActionPerformed

    private void btn_addClientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addClientActionPerformed
        if(tf_origin.getText().toString().length() != 0 && tf_destiny.getText().toString().length() != 0){
            char origin = tf_origin.getText().toString().charAt(0);
            char destiny = tf_destiny.getText().toString().charAt(0);
            if(!simulation.addClients(origin, destiny)){
                System.out.println("Error: Origen \'" + origin + "\' Destino \'" + destiny + "\' es invalido para parquear");
            }
        } 
    }//GEN-LAST:event_btn_addClientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        simulation = new Taxi();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input().setVisible(true); 
            }
        });

        new Thread(simulation).start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addClient;
    private javax.swing.JButton btn_animate;
    private javax.swing.JButton btn_cantClients;
    private javax.swing.JButton btn_mode;
    private javax.swing.JButton btn_park;
    private javax.swing.JButton btn_path;
    private javax.swing.JButton btn_route;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JRadioButton rb_parade;
    private javax.swing.JRadioButton rb_search;
    private javax.swing.ButtonGroup taxiModeGroup;
    private javax.swing.JTextField tf_animate;
    private javax.swing.JTextField tf_cantClients;
    private javax.swing.JTextField tf_destiny;
    private javax.swing.JTextField tf_origin;
    private javax.swing.JTextField tf_park;
    // End of variables declaration//GEN-END:variables
}
